variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}
variable "db_server" {}
variable "db_port" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
