apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: api
        image: mycontainerregistrytechchallenge.azurecr.io/store:dev
        env:
        - name: DefaultConnection
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DefaultConnection
        ports:
        - containerPort: 8080
        - containerPort: 8081
