apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: default
type: Opaque
data:
  DefaultConnection: "U2VydmVyPW15ZGF0YWJhc2V0ZWNoY2hhbGxlbmdlLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPW15ZGF0YWJhc2V0ZWNoY2hhbGxlbmdlO1VzZXIgSUQ9YWRtaW5fdXNlcjsgUGFzc3dvcmQ9Uzh0cjBuZyFQYXNzIzIwMjREYiE7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVl"