name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login no Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: mycontainerregistrytechchallenge.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build e Push da imagem 'store'
      uses: docker/build-push-action@v4
      with:
        context: ./store
        push: true
        tags: mycontainerregistrytechchallenge.azurecr.io/store:dev

    - name: Build e Push da imagem 'payment'
      uses: docker/build-push-action@v4
      with:
        context: ./payment
        push: true
        tags: mycontainerregistrytechchallenge.azurecr.io/payment:dev

    - name: Login no Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANTID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}  

    - name: Configurar kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Obter credenciais do AKS
      run: az aks get-credentials --resource-group myResourceGroup --name myAKSCluster --overwrite-existing

    - name: Aplicar manifests no Kubernetes
      run: kubectl apply -f k8s/
